### PR TITLE
TX Nonces

### LINKED ISSUE #1521: [WalletConnect] Nonce not respected
**Scenario**:
Using https://cancel-ethereum-transactions.web.app/ to speed up or cancel a transaction.

**Expected result**:
Nonce set by dapp is respected.

**Actual result**:
Nonce set by dapp is not respected.

**Example**:
Original transaction: https://etherscan.io/tx/0x2f703b2cd455e44a07caca3f1dcd33c6cfa2d88f6d6e344c5744c3b151823fad
Attempt to speed up transaction with Rainbow (wrong nonce): https://etherscan.io/tx/0x50d5f5d471857158681ea6674956fbf05afa9a55d1da33d9a89f5c03cc97225c
Attempt to speed up transaction with Trust Wallet (correct nonce): https://etherscan.io/tx/0xfc0083e05a974f8b594a5d99d4bf182bbef0701ae6719381a058fe1388cf272d

**Rainbow version**:
Android; 1.0 (11)

### PR DESCRIPTION
**Pull request by brunobar79**
- Allow dapps to pass a nonce via WC (Fixes #1521)
- Remove all local nonce logic and use / store the nonce from tx receipt instead
- Make speed up / cancel sheet to always use the nonce from the tx receipt
- Fix race condition where sometime the nonce was higher than it should while saving the tx data in the state (mentioned in Slack)

@skylarbarrera  We need to QA:
- all types of send ( ETH / ERC20 / NFT)
- all raps (unlock / swap / deposit / witthdraw) 
- Speed up & cancel

### CODE REVIEW

File: src/screens/SpeedUpAndCancelSheet.js [hunk 1]
```diff
@@ -132,9 +132,11 @@ export default function SpeedUpAndCancelSheet() {
   const [minGasPrice, setMinGasPrice] = useState(
     calcMinGasPriceAllowed(tx.gasPrice)
   );
+  const fetchedTx = useRef(false);
   const [gasLimit, setGasLimit] = useState(tx.gasLimit);
   const [data, setData] = useState(tx.data);
   const [value, setValue] = useState(tx.value);
+  const [nonce, setNonce] = useState(tx.nonce);
```
Comment (jinchung) [inline src/screens/SpeedUpAndCancelSheet.js:139]: Given that gasLimit, data, value, nonce are mainly set together and used together, should we have one useState "txPayload" or something instead of having these all separate?

File: src/screens/TransactionConfirmationScreen.js [hunk 2]
```diff
@@ -420,30 +418,26 @@ const TransactionConfirmationScreen = () => {
       }
     }
 
-    const web3TxnCount = await getTransactionCount(txPayload.from);
-    const maxTxnCount = Math.max(transactionCountNonce, web3TxnCount);
-    const nonce = maxTxnCount;
     const calculatedGasLimit = gas || gasLimitFromPayload || gasLimit;
-    let txPayloadLatestNonce = {
+    let txPayloadUpdated = {
```
Comment (jinchung) [inline src/screens/TransactionConfirmationScreen.js:422]: We can now remove redux/nonce and any references to `updateTransactionCountNonce` and `nonceClearState`

**Comment by jinchung** [comment]
This is great! Thank you @brunobar79 

A couple things for convo:
1. Just confirming that for this version: if a dapp sends us a nonce through WC, we are now using that nonce regardless?
2. We are now no longer sending along nonces when sending transactions and instead relying on our nodes? (If so, we used to see some intermittent issues when nodes would be out of sync, so we may want to keep this in mind for a more robust option.)
We can merge this in first as we were not consistent about our nonce-sending before anyway. @skylarbarrera  if you don't mind trying it out with multiple transactions sent out while others are still pending.

**Comment by brunobar79** [comment]
@jinchung  About  1 - Yes, now we are passing the wc tx payload as it is and overriding the gas.

About 2 - Notice that I've removed the nonce for WC and send ETH only, to send multiple transactions in those scenarios it very likely that it takes you at least one block (~13 sec) so it's less likely to happen.  We were not sending nonces for any of the rap actions and I didn't change that.  I

MO to fully solve that problem we should migrate to alchemy which solves the out of sync issue.

File: src/screens/SpeedUpAndCancelSheet.js (hunk 1 above)
Comment (brunobar79) [reply src/screens/SpeedUpAndCancelSheet.js:139]: I prefer to keep it as it is so I can "pre-populate" with the values from tx. Otherwise I have to add a bunch conditionals after.

**Review by skylarbarrera — APPROVED** [review]
Tested:
Send ETH, ERC20, NFT, cancel & speed up, all pending at same time.

Deposit + Withdraw, cancel, while others were pending.

Swap, 1 w approval & a few without, cancel & speed up as well, while multiple we're pending

Race condition seems handled as I had ~9 transactions pending and was able to cancel/speed up totally fine.

Lmk if I missed anything!

**Review by jinchung — APPROVED** [review]
🌮
